### ISSUE TITLE
SCS versus interior point method for small (dim<100 or dim<10?) SDP problems

### ISSUE THREAD

**Issue by hitdshu** [cvxgrp/scs#159]
Hi, 

I'd like to choose some c/c++ solvers for small SDP problems in computer vision/robotics. It is demonstrated in the paper that SCS is far more efficient for large problems. So how is SCS performing when the problem is small? Does it still  have comparable performance to other solvers(like SDPT3/SDPA/CSDP)?

**Comment by bodono** [comment]
I think it would depend on your use case. If you want very high accuracy then a first-order method like SCS is not going to be fastest, but if moderate accuracy is required then SCS can be faster. I think you would really have to experiment and see what works. It shouldn't be too hard to test SCS if you are already able to call the other solvers since SCS has a similar API.

**Comment by hitdshu** [comment]
> I think it would depend on your use case. If you want very high accuracy then a first-order method like SCS is not going to be fastest, but if moderate accuracy is required then SCS can be faster. I think you would really have to experiment and see what works. It shouldn't be too hard to test SCS if you are already able to call the other solvers since SCS has a similar API.

Thanks for your reply. I'll try it, and let's hope SCS wins.
