### ISSUE TITLE
Objective value of certificates

### ISSUE THREAD

**Issue by odow** [cvxgrp/scs#185]
JuMP is trying to standardize our handling of infeasibility certificates:
https://github.com/jump-dev/MathOptInterface.jl/pull/1660
https://jump.dev/MathOptInterface.jl/previews/PR1660/background/infeasibility_certificates/

One open question is what to do for the primal objective value (if dual infeasible) or the dual objective value (if primal infeasible).
We've come to the conclusion that we should use the objective evaluated at the ray, excluding constant terms.

SCS currently sets them to `(-)INFINITY`:
https://github.com/cvxgrp/scs/blob/6ef145b630733095eaaaf57dbd51fa48fd1bba98/src/scs.c#L474-L498

We can carry a specific fix in SCS.jl (which doesn't include the quadratic objective terms yet):
https://github.com/jump-dev/SCS.jl/pull/233/files
so just opening this issue to see if there is any interest in carrying this convention upstream.

**Comment by bodono** [comment]
I do not think that setting the objective value to be the ray objective value is the correct thing to do, for a few reasons:

1. The *actual* objective value of a feasible primal unbounded problem (dual infeasible) is -infinity, and strong duality holds so p* = d* = -inf, and similarly for feasible dual unbounded (strong duality does not hold if both primal and dual are infeasible, but this is rare).
2. I think it would be confusing to the user to return a different value, and possibly introduce bugs, especially if the primal variable is also populated with the certificate value.
3. The objective value of the ray is not well defined, since it is a homogeneous ray it can take any value by scaling. SCS returns a certificate that always produces -1 when evaluated in the objective. 
4. If the user wants to compute some value of the ray, they can do that very quickly themselves, though it's rare that a user would actually care about that value since, as I mentioned, it is not well defined.

**Comment by odow** [comment]
Fully agree, and I see why you don't want to add this to SCS.

It isn't entirely obvious what to do, and things are ill-defined. (And no one has come complaining about this in JuMP, so it obviously isn't that important to users.) 

Our reasoning is:

 * JuMP has a specific "TerminationStatus" which can return "DUAL_INFEASIBLE" if unbounded, and a "PrimalStatus" which can return "INFEASIBILITY_CERTIFICATE" if it found a ray, and "FEASIBLE_POINT" if it proved dual infeasibility but is returning a primal point, so we aren't worried about people mis-interpreting the solutions.
 * For dual infeasible problems, the variable primal solution is the ray.
 * What should the other primal solution attributes be? i.e., the primal objective value and the constraint primal solution.
   * We could choose to make these `NaN` or similar and say they aren't well defined since they can be anything
   * Or we can choose to make them the evaluation of the objective and constraint at the ray, excluding the constant terms

Either option is defensible, so we've gone for the second option. It's more about explicitly documenting the convention, rather than it being of high importance to users.

Happy to close this. I'll move the change in SCS.jl to the MOI wrapper so we don't interfere with the behavior of the C API.

**Comment by blegat** [comment]
> I think it would be confusing to the user to return a different value, and possibly introduce bugs, especially if the primal variable is also populated with the certificate value.

This is consistent to the design decision made at JuMP. Because it's still considered low-level and want to be flexible to cover all use cases, we try the solutions to convey as much information as possible. We don't even throw a warning when the uses gets the `value` or dual value without checking the status. The reasoning is that it's the responsibility of packages built on JuMP to do these checks and never blindly get solutions without checking the status.
Note that I used a similar argument for returning the current solution when the solver has not converged (https://github.com/cvxgrp/scs/pull/169#issuecomment-913828834).

> If the user wants to compute some value of the ray, they can do that very quickly themselves, though it's rare that a user would actually care about that value since, as I mentioned, it is not well defined.

I did needed this value in https://github.com/JuliaStochOpt/StructDualDynProg.jl. When the problem is infeasible or unbounded, you can use the certificate (both variables values/constraint dual and objective value / objective dual value) to generate cuts.

**Comment by odow** [comment]
Closing because we'll handle this in SCS.jl.

**Comment by bodono** [comment]
I think ideally this would be handled by JuMP and the SCS interfaces would be consistent with each other, but I'll leave it to you.

**Comment by odow** [comment]
Yip, that's what I've done. If you use the `SCS.scs_solve` method which wraps the C interface, you get the standard behavior. You'll only see this modified behavior if you use the JuMP/MathOptInterface interface.

**Comment by bodono** [comment]
Oh ok, sounds good.
