### ISSUE TITLE
cvx_install_scs missing?

### ISSUE THREAD

**Issue by dvij** [cvxgrp/scs#34]
Hi,
I can't find the cvx_install_scs file. Is it bundled with cvx? I'm using CVX professional version 2.1, and I don't see it anywhere in the cvx folder.

Thanks,
Dj

**Comment by bodono** [comment]
Hi Dj,

Right now SCS is targeting the cvx 3.0b beta version, because Michael Grant has made a native shim for SCS in that branch that includes useful things like being able to target exponential cones etc. and the interface for SCS has changed since it was compatible with CVX 2.1. To use with CVX 3.0b you install SCS with the make_scs command, then add the path using 'addpath /path/to/scs/matlab' then run cvx_setup and it should pick it up. Is it possible to use CVX 3.0b for your use case?

http://cvxr.com/cvx/beta/

Brendan

**Comment by rocketdude** [comment]
Hi @bodono,
Is this still the current plan or has there been any changes? I'm interested in using the cvxquad library which only works on CVX 2.1. It'd be nice if we can solve the SDPs with SCS.

**Comment by bodono** [comment]
No unfortunately it's not compatible with cvx  < 3.0, it's because of CVX not because of SCS though.
