### ISSUE TITLE
out of memory GPU error

### ISSUE THREAD

**Issue by btabibian** [cvxgrp/scs#50]
Hi,

I have been experimenting with the GPU version and managed to run out of memory! Is there any documentation of how the GPU implementation works? is there a way to address the memory issue?

**Comment by bodono** [comment]
Your GPU will have its own on-board memory that SCS ships the data to. Usually this memory is smaller than the host memory, so you can run into OOM issues. To see how much you have (and how much is in use) you can type `nvidia-smi`.

**Comment by btabibian** [comment]
Do you think there is possibility of streaming data to GPU or it is necessary to load all data on GPU?

**Comment by bodono** [comment]
Well right now it sends everything to the GPU at the same time. Making it stream data over would require a fair amount of work, and might not actually be worth it as transferring the data over is quite expensive.

One way to double the amount of data you can send to the GPU is to compile it to run with single precision floats, rather than double precision (GPUs are faster for single precision anyway). To do that you have to pull down the latest version of SCS, type in the scs directory:

`make purge && make FLOAT=1 && make gpu FLOAT=1`

Move the llibscsgpu.so to wherever, e.g. `/usr/local/lib`. Then uncomment [this line](https://github.com/cvxgrp/scs/blob/560158d0658ac2aab53e30a575e0154504460ced/python/setup.py#L24) to compile the python module with floating point.

Then re-run python setup.py install.

The version of blas I have installed on my laptop doesn't support single precision for some reason, so you might have trouble solving SDPs if you do this.

**Comment by btabibian** [comment]
@bodono Thanks for the suggestions. I will try the single precision. I guess that should work for my problem.

**Comment by bodono** [comment]
I just made some changes that should make it easier to compile the GPU python code. When installing use
```
python setup.py install --scs --gpu
```
(you might need sudo) and for single precision add `--float` at the end.
