### ISSUE TITLE
parallelization factor using openMP

### ISSUE THREAD

**Issue by btabibian** [cvxgrp/scs#53]
Hi,

I am using OpenMP version of SCS solver, I would like to know what are the factors that can impact number of threads used for solving a problem. 

In particular, I have a machine with 20 cores, specifying `OMP_NUM_THREAD=20` uses only 10 of the 20 cores and increasing number of cores does not change the actual number of cores used.

**Comment by bodono** [comment]
I would say the main factor (other than OMP_NUM_THREADS) is the sparsity pattern of the data matrix A. For example, if A has one column (or row) with N >> 1 non-zeros, and all the other columns have just 1 non-zero, then it will *look* like you're only using one thread because the thread that gets the column with N non-zeros will take a lot longer to finish than the others. I would take a look at the sparsity pattern of A and see if there is some unbalanced rows or columns.

There could potentially be some other factors relating to the operating system giving you threads that I don't know about too, but the sparsity pattern issue is one I have encountered before.

**Comment by btabibian** [comment]
thanks, is there a way to get matrix A from inside CVXPY?

**Comment by btabibian** [comment]
Never mind, found it in the documentation.

**Comment by ajfriend** [comment]
For a CVXPY Problem object 'prob',

data = prob.get_problem_data('SCS')

will return a dictionary with the SCS inputs.

For reference, it's documented here:
http://www.cvxpy.org/en/latest/tutorial/advanced/index.html#getting-the-standard-form

**Comment by WellWellww** [comment]
> I would say the main factor (other than OMP_NUM_THREADS) is the sparsity pattern of the data matrix A. For example, if A has one column (or row) with N >> 1 non-zeros, and all the other columns have just 1 non-zero, then it will _look_ like you're only using one thread because the thread that gets the column with N non-zeros will take a lot longer to finish than the others. I would take a look at the sparsity pattern of A and see if there is some unbalanced rows or columns.
> 
> There could potentially be some other factors relating to the operating system giving you threads that I don't know about too, but the sparsity pattern issue is one I have encountered before.

May I ask how do we avoid the situation that multi-threading becomes a single thread when some threads cost much more time than the others

**Comment by kalmarek** [comment]
@WellWellww since your problems are really large (https://discourse.julialang.org/t/largest-number-of-variables-that-scs-jl-can-handle/100929/12) I'd argue that trying to reduce their sizes is a much better way to address the problem, instead of making better use of multithreading here.

And of course you should try the MKL linear solver first ;)

**Comment by WellWellww** [comment]
> @WellWellww since your problems are really large (https://discourse.julialang.org/t/largest-number-of-variables-that-scs-jl-can-handle/100929/12) I'd argue that trying to reduce their sizes is a much better way to address the problem, instead of making better use of multithreading here.
> 
> And of course you should try the MKL linear solver first ;)

Oh, I really appreciate your suggestions! I have tried MKL linear solver as soon as I received your reply and the program is still running and has not finished yet. Indeed it is not as easy to simplify the problem, though I am certainly working on this. In fact I'm asking for this because I met another question of general use (https://discourse.julialang.org/t/multi-threading-appears-to-be-single-thread-when-some-threads-cost-much-more-time-than-the-others/101353), and I saw the post here by accident and asked incidentally. Maybe this is not a correct place to ask this question... sorry.
