### ISSUE TITLE
is there any example about SDP in c++

### ISSUE THREAD

**Issue by wangdingkang** [cvxgrp/scs#66]
I just installed scs, and I'm using it in c++. I have an SDP problem, a matrix X, entries of it are variables. There are some linear constraints on its entries, including some equations and inequalities.

For example, X is a 2 * 2 symmetric semidefinite matrix, I want X[1, 1] - X[1, 2] >= 0, X[1, 1] - X[2, 2] <=5, something like that. I don't have a objective, but just want to find out a feasible solution.

Can you give an more detailed tutorial, I know I need to build a Data, and a Cone, but don't know how, thank you.

**Comment by bodono** [comment]
Firstly, I would recommend letting a parser form the problem for you, e.g. [CVXPY](http://www.cvxpy.org/en/latest/), which lets you write the problem in a natural language and it will form the correct data format and call SCS.

If you really need to form it yourself, your best bet is to get familiar with cone programming from the literature, e.g., [convex optimization](http://www.stanford.edu/~boyd/cvxbook/bv_cvxbook.pdf). In short, what you need to do is get your problem into the primal form:
```                       
minimize        c'x       
subject to      Ax + s = b
                s in K    
```                       
so you need to form A, b,c so that the problem above is equivalent to your problem specification. SDPs are a little tricky because you only specify the lower triangular elements, and you do some scaling. See the README for more information.
