### ISSUE TITLE
Divergent-looking behavior on a problem that ECOS solves

### ISSUE THREAD

**Issue by RhysU** [cvxgrp/scs#78]
I've a modest size problem (created via cvxpy 0.4.8) where ECOS tells me it has found an optimum, albeit after an unexpectedly large number of iterations.  SCS, for direct/indirect, will happily churn away on the same problem for as many iterations as I give it.  SCS settles into a pattern where the 'pri obj' grows with iteration number.  Per a comparison table at http://www.cvxpy.org/en/latest/tutorial/advanced/index.html#solve-method-options I expected ECOS and SCS to both be able to solve the same problem given unbounded time.  Am I misunderstanding the amount to which one can be substituted for another?  Likelihood of something amiss in cvxpy or SCS?

**Comment by bodono** [comment]
In theory SCS can solve any problem of a form it accepts given unlimited time. In practice bad numerical conditioning in the problem can make it fail. The fact that ECOS (a second-order method) took a long time to converge would indicate that the problem is poorly conditioned, and so SCS (a first order method) would also struggle.

**Comment by RhysU** [comment]
Thank you-- I will look into the conditioning.  Much appreciate the advise, as I'm new to the space.
