### ISSUE TITLE
SCS out not Converging

### ISSUE THREAD

**Issue by prateeky2806** [cvxgrp/scs#99]
I am trying to solve an SDP on GPU. The size of the matrix involved is ~1000 but even after running the solver with 50000 iterations the solution it is returning has status Solved/Inaccurate. The tolerance level I need is around 1e-07.  Before this particular graph, I have used the same code for much larger matrices and it converges within 1000 iterations.

        ----------------------------------------------------------------------------
	SCS v2.0.2 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012-2017
        ----------------------------------------------------------------------------
       Lin-sys: sparse-indirect GPU, nnz in A = 1519212, CG tol ~ 1/iter^(2.00)
       eps = 1.00e-07, alpha = 1.50, max_iters = 50000, normalize = 1, scale = 1.00
       acceleration_lookback = 20, rho_x = 1.00e-03
       Variables n = 508537, constraints m = 1518204
       Cones:	primal zero / dual free vars: 1009668
       sd vars: 508536, sd blks: 1
       Setup time: 1.37e+00s
       ----------------------------------------------------------------------------
        Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
       ----------------------------------------------------------------------------
       0| 1.48e+22  7.53e+21  1.00e+00 -5.09e+23  4.05e+23  4.87e+20  1.67e+00 
       100| 4.23e-02  1.09e-03  4.26e-04  4.07e+02  4.07e+02  7.60e-15  5.38e+01 
       200| 3.58e-02  9.64e-04  3.08e-04  4.15e+02  4.15e+02  3.87e-16  1.03e+02 
       300| 3.07e-02  9.14e-04  3.58e-05  4.16e+02  4.16e+02  2.10e-14  1.54e+02
       23800| 5.42e-03  1.67e-04  4.60e-05  4.13e+02  4.13e+02  1.98e-13  1.09e+04 
       23900| 1.18e-04  3.20e-06  2.11e-06  4.13e+02  4.13e+02  8.97e-15  1.10e+04 
       24000| 6.74e-05  1.71e-06  3.20e-07  4.13e+02  4.13e+02  1.89e-14  1.10e+04 
       24100| 1.21e-04  2.90e-06  3.06e-06  4.13e+02  4.13e+02  1.68e-15  1.11e+04 
       24200| 1.06e-04  2.89e-06  7.31e-07  4.13e+02  4.13e+02  8.38e-15  1.11e+04 
       49400| 9.43e-05  2.71e-06  1.46e-06  4.13e+02  4.13e+02  1.53e-14  2.23e+04 
       49500| 1.28e-04  3.45e-06  7.60e-07  4.13e+02  4.13e+02  9.91e-16  2.23e+04 
       49600| 3.60e-03  9.34e-05  1.07e-05  4.13e+02  4.13e+02  1.31e-13  2.23e+04 
       49700| 6.06e-05  1.60e-06  3.10e-07  4.13e+02  4.13e+02  6.74e-16  2.24e+04 
       49800| 1.45e-04  4.07e-06  6.35e-07  4.13e+02  4.13e+02  1.47e-14  2.24e+04 
       49900| 9.53e-05  2.99e-06  1.33e-07  4.13e+02  4.13e+02  5.72e-15  2.25e+04 
       50000| 2.24e-04  6.33e-06  5.12e-07  4.13e+02  4.13e+02  2.11e-14  2.25e+04 
       ----------------------------------------------------------------------------
       Status: Solved/Inaccurate
       Hit max_iters, solution may be inaccurate
       Timing: Solve time: 2.25e+04s
       Lin-sys: avg # CG iterations: 3.00, avg solve time: 1.28e-01s
       Cones: avg projection time: 6.56e-02s
       Acceleration: avg step time: 2.07e-01s
       ----------------------------------------------------------------------------
       Error metrics:
       dist(s, K) = 5.3764e-02, dist(y, K*) = 1.2347e-06, s'y/|s||y| = -2.2028e-10
       primal res: |Ax + s - b|_2 / (1 + |b|_2) = 2.2388e-04
       dual res:   |A'y + c|_2 / (1 + |c|_2) = 6.3261e-06
       rel gap:    |c'x + b'y| / (1 + |c'x| + |b'y|) = 5.1194e-07
       ----------------------------------------------------------------------------
       c'x = 413.1845, -b'y = 413.1849
       ============================================================================
        Time to Solve Optimisation: 22537.750083208084 seconds

I am not sure, what exactly is the issue here. Any help will be appreciated.

**Comment by bodono** [comment]
Thanks for posting this, do you have a script or the data for this problem that I can test with myself?

**Comment by bodono** [comment]
My guess is that the problem size is making the acceleration poorly conditioned and it's having trouble. You could try running it with `acceleration_lookback = 5` or even `acceleration_lookback = 0`,  doing that will also make it run faster _per iteration_, since from the timing data it turns out for your problem the acceleration is actually the slowest step (which is not good). 

If you have the data or a script I can try digging in and trying a few things myself.

**Comment by prateeky2806** [comment]
Hi @bodono 
Yes, I have the data and the code, how can I send it to you?

**Comment by bodono** [comment]
You can email me at bodonoghue85@gmail.com if that works for you?

**Comment by prateeky2806** [comment]
Hi @bodono 
I have sent the email.

**Comment by bodono** [comment]
I played around a lot with your example with lots of different settings, both on GPU and CPU, direct and indirect etc. And I couldn't get it to solve to tighter than 1e-5 accuracy within the 50k steps you specified. In theory SCS will converge to arbitrary precision, but in practice numerical errors and inaccuracies might limit how close it (or any solver) can get, or slow down convergence to a crawl. Since you have around 1M variables, getting a residual with a norm of 1e-5 is actually something like an average tolerance of 1e-11 for each variable (very loosely speaking). This might be getting close to the limit of numerical accuracy, although I suspect it's actually closer to the limit of what the algorithm can tolerate in order to be able to make numerical progress. By that I mean you could find the true solution using some other method, or because you know it in advance, and you calculated the residuals then they would get smaller norms than 1e-5, but SCS is having trouble making progress because the update directions are 'noisy', although it is very slowly converging using the direct solver on CPU with `acceleration_lookback = 0`. I just kicked off running for 500k steps, so let's see how that does.

**Comment by bodono** [comment]
After 500k it gets:
```
500000| 8.58e-08  1.25e-07  2.21e-10  4.13e+02  4.13e+02  8.44e-14  7.30e+04
----------------------------------------------------------------------------
Status: Solved/Inaccurate                                                   
Hit max_iters, solution may be inaccurate                                   
Timing: Solve time: 7.30e+04s                                               
        Lin-sys: nnz in L factor: 3545953, avg solve time: 3.03e-02s        
        Cones: avg projection time: 6.43e-02s                               
        Acceleration: avg step time: 0.00e+00s                              
----------------------------------------------------------------------------
Error metrics:                                                              
dist(s, K) = 1.9552e-09, dist(y, K*) = 2.3992e-09, s'y/|s||y| = -1.4965e-13 
primal res: |Ax + s - b|_2 / (1 + |b|_2) = 8.5798e-08                       
dual res:   |A'y + c|_2 / (1 + |c|_2) = 1.2505e-07                          
rel gap:    |c'x + b'y| / (1 + |c'x| + |b'y|) = 2.2053e-10                  
----------------------------------------------------------------------------
c'x = 413.1930, -b'y = 413.1930                                             
============================================================================
```
So almost the 1e-7 accuracy. This run took about 3x longer than your run, according to the timing.

**Comment by prateeky2806** [comment]
@bodono thanks for looking into the problem. I have tried other solver but none of them does better than SCS, so that direction is closed. I guess I'll work with the accuracies I get from SCS only. 
Thank you again for the help. 
PS: Should I close this issue?

**Comment by bodono** [comment]
No problem.
